version: '4.4'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: RecipeMaker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: glebtosee
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - HOST=db
      - PORT=5432
      - DBNAME=RecipeMaker
      - USER=postgres
      - PASSWORD=glebtosee
    depends_on:
      db:
        condition: service_healthy